//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamaciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ReclamacionesEntities1 : DbContext
    {
        public DB_ReclamacionesEntities1()
            : base("name=DB_ReclamacionesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Observador> Observadors { get; set; }
        public virtual DbSet<Reclamacion> Reclamacions { get; set; }
        public virtual DbSet<Tipo_Reclamacion> Tipo_Reclamacion { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
