//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclamaciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamacion
    {
        public int Id_Reclamacion { get; set; }
        public Nullable<int> Tipo_Reclamacion { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Descripcion { get; set; }
        public string Detalle { get; set; }
        public string Ubicacion_Campus { get; set; }
        public string Ubicacion_Edificio { get; set; }
        public Nullable<int> Observador { get; set; }
        public Nullable<int> Usuario { get; set; }
        public System.DateTime Fecha_Reclamacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Observador Observador1 { get; set; }
        public virtual Tipo_Reclamacion Tipo_Reclamacion1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
